// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYoCFfnSeWX0Jfk3LnyATzh24hIed-c50',
    appId: '1:663133939368:web:b098b97b64d82f0547449d',
    messagingSenderId: '663133939368',
    projectId: 'bluefang-a67df',
    authDomain: 'bluefang-a67df.firebaseapp.com',
    storageBucket: 'bluefang-a67df.appspot.com',
    measurementId: 'G-Z1SN0PYVLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyCff5I6lkDlNuhBx940Y7wSSxm6ub_3A',
    appId: '1:663133939368:android:041833087962acb947449d',
    messagingSenderId: '663133939368',
    projectId: 'bluefang-a67df',
    storageBucket: 'bluefang-a67df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRzJPQH9_ne-jjqby6uhoXe3t_G7F6ueg',
    appId: '1:663133939368:ios:1538f51cec8b22fe47449d',
    messagingSenderId: '663133939368',
    projectId: 'bluefang-a67df',
    storageBucket: 'bluefang-a67df.appspot.com',
    iosClientId: '663133939368-t5kctalq4680dmp769pit8smhscqu0l0.apps.googleusercontent.com',
    iosBundleId: 'com.stemco.1234',
  );
}
